### ISSUE TITLE
How to add a menu?

### ISSUE THREAD

**Issue by Theneum** [Vimux/blank#10]
Thanks for creating this, it's really helped me get started with Hugo. Being really new to Hugo however, it's not intuitive to me how to add a menu. Looks like it should be added in the config file? Would be great to have an example.

**Comment by Theneum** [comment]
I got it sorted just fine but still think it would be nice to have an example in the readme at least.

**Comment by ijsucceed** [comment]
Thanks for showing interest. I will add an example in the readme.

Still, since you already figured it out, why not contribute to the theme by adding the example in the readme.

Appreciated, if you do.
