### ISSUE TITLE
[Question] How does the routing works?

### ISSUE THREAD

**Issue by wsw70** [Vimux/blank#18]
First of all - thank you for this, it is of great help when starting a theme.

I am new to Hugo (but have coded since 1994) and I cannot understand how the routing works in your theme. I am sure that this is something that is explained somewhere in Hugo docs but I cannot find it anywhere. Feel free to RTFM me with the link :)

Specifically, my problem is that I do not see where the main skeleton for the final web page is - that one that will build `<header>`, `<body>`, etc. I expected to find there the logic of switching between views: what to parse when looking at the remaining page, what at a blog entry, what at a standalone page, etc.

I see `https://github.com/Vimux/blank/tree/master/layouts/index.html`, but it is just the definition of **one of the** `main` blocks. There are other such definitions in `https://github.com/Vimux/blank/tree/master/layouts/_default` for instance.

**Where do I code the logic/decision to use one file (with the def of `main`) or another?**

I expect that some "routing" (not dynamic one - a routing that is then compiled into a set of pages with links to other pages) must be defined somewhere where you say that the page `/` is generated from `<something>`  and a page `/blog:hello-world` is generated from  `<something else>`. The thing that drives me crazy is that I know it's probably simple and I see the correct structure when looking,g at actual pages through DevTools.

**Comment by Vimux** [comment]
https://gohugo.io/templates/base/
