### ISSUE TITLE
Unable to find archetypes directory for theme "blank"

### ISSUE THREAD

**Issue by up4digital** [Vimux/blank#4]
Dear Vimux,

I'm using your cool theme as a git submodule on my fresh Hugo installation and I've noticed that when I create a new post with command "hugo new posts/name-of-my-post.md" I get the annoying error message "**Unable to find archetypes directory for theme "blank**"" (even if anyway the post is correctly created)

Reading here:
https://github.com/devcows/hugo-universal-theme/issues/16
it seems this kind of error message occurs because the theme didn't have a archetypes directory...

I was wondering if you are aware of it and maybe you want to add an empty archetypes directory in the repository to avoid this error...

Thanks for your good work

fabio

**Comment by Vimux** [comment]
@up4digital, thank you for report. I add default archetype, error should be gone.
