### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [Vimux/blank#9]
Hello!

I found the problem exactly the same as one by link https://github.com/dim0627/hugo_theme_beg/issues/19:
![image](https://user-images.githubusercontent.com/712534/37654292-a5e25320-2c52-11e8-9a6d-6de7a4dc8d0d.png)

**Comment by Vimux** [comment]
Blank theme contains blank style.css (it means zero lines of css code). So, it's not a bug.
